# Generated by Django 3.0.8 on 2021-02-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210212_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='images'),
        ),
    ]
